"use client";

import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { ProductShell } from "@/components/product-shell";
import { Check,Clock3,Plus,Workflow,X } from "@/components/icons";
import { apiData,loadWorkspace } from "@/lib/client-api";

type Step={id:string;node_id:string;node_type:string;status:string;error:string|null;started_at:string;finished_at:string|null};
type Run={id:string;status:string;attempt:number;current_node_id:string|null;state:Record<string,unknown>;started_at:string;finished_at:string|null;workflow_run_steps:Step[]};
type Version={version:number;graph:{nodes:Array<{id:string;type:string}>;edges:Array<Record<string,unknown>>};published_at:string|null};
type Flow={id:string;name:string;status:string;active_version:number|null;updated_at:string;workflow_versions:Version[];workflow_runs:Run[]};
const stages=["","lead","qualified","opportunity","customer","repeat_customer","win_back","inactive"];
const pretty=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,(item)=>item.toUpperCase());

function buildGraph(keyword:string,reply:string,delaySeconds:number,lifecycleStage:string,note:string){
  const nodes:Array<Record<string,unknown>>=[{id:"incoming",type:"trigger",config:{event:"message.received"}}];const edges:Array<Record<string,unknown>>=[];let source="incoming";
  if(keyword.trim()){nodes.push({id:"keyword",type:"condition",config:{operator:"contains",value:keyword.trim()}});edges.push({source,target:"keyword"});source="keyword";nodes.push({id:"handoff",type:"assign",config:{}},{id:"fallback_end",type:"end"});edges.push({source:"keyword",target:"handoff",branch:"false"},{source:"handoff",target:"fallback_end"});}
  const chain:string[]=[];
  if(delaySeconds>0){nodes.push({id:"wait",type:"delay",config:{seconds:delaySeconds}});chain.push("wait")}
  if(lifecycleStage){nodes.push({id:"contact_update",type:"contact",config:{lifecycleStage}});chain.push("contact_update")}
  if(note.trim()){nodes.push({id:"internal_note",type:"note",config:{body:note.trim()}});chain.push("internal_note")}
  nodes.push({id:"reply",type:"message",config:{content:{type:"text",text:reply}}},{id:"complete",type:"end"});chain.push("reply","complete");
  edges.push({source,target:chain[0],...(keyword.trim()?{branch:"true"}:{})});for(let index=0;index<chain.length-1;index++)edges.push({source:chain[index],target:chain[index+1]});
  return{nodes,edges};
}

export default function AppWorkflows(){
  const[tenantId,setTenantId]=useState("");const[flows,setFlows]=useState<Flow[]|null>(null);const[open,setOpen]=useState(false);const[name,setName]=useState("");const[keyword,setKeyword]=useState("");const[reply,setReply]=useState("Thanks for your message. A team member will reply shortly.");const[delay,setDelay]=useState(0);const[stage,setStage]=useState("");const[note,setNote]=useState("");const[busy,setBusy]=useState(false);const[publishing,setPublishing]=useState("");const[retrying,setRetrying]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");
  const load=useCallback(async(signal?:AbortSignal)=>{const workspace=await loadWorkspace(signal);if(!workspace.workspace)throw new Error("No active workspace is available");setTenantId(workspace.workspace.id);setFlows(await apiData<Flow[]>(`/api/v1/workflows?tenantId=${workspace.workspace.id}`,{signal}))},[]);
  useEffect(()=>{const controller=new AbortController();load(controller.signal).catch(value=>{if(value instanceof Error&&value.name!=="AbortError")setError(value.message)});return()=>controller.abort()},[load]);
  const totals=useMemo(()=>({active:flows?.filter(flow=>flow.status==="active").length??0,runs:flows?.reduce((sum,flow)=>sum+(flow.workflow_runs?.length??0),0)??0,failed:flows?.reduce((sum,flow)=>sum+(flow.workflow_runs?.filter(run=>run.status==="failed").length??0),0)??0}),[flows]);
  async function create(event:FormEvent){event.preventDefault();setBusy(true);setError("");setNotice("");try{await apiData("/api/v1/workflows",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tenantId,name,graph:buildGraph(keyword,reply,delay,stage,note)})});setOpen(false);setName("");setKeyword("");setDelay(0);setStage("");setNote("");setNotice("Versioned workflow draft created. Review its nodes before publishing.");await load()}catch(value){setError(value instanceof Error?value.message:"Workflow could not be created")}finally{setBusy(false)}}
  async function publish(flow:Flow){const version=Math.max(...flow.workflow_versions.map(item=>item.version),1);if(!window.confirm(`Publish version ${version} of “${flow.name}”? New inbound messages can trigger it immediately.`))return;setPublishing(flow.id);setError("");try{await apiData(`/api/v1/workflows/${flow.id}/publish`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({version})});setNotice(`${flow.name} is active for new inbound messages.`);await load()}catch(value){setError(value instanceof Error?value.message:"Workflow could not be published")}finally{setPublishing("")}}
  async function retry(run:Run){setRetrying(run.id);setError("");try{await apiData(`/api/v1/workflows/runs/${run.id}/retry`,{method:"POST"});setNotice(`Workflow run retry ${run.attempt+1} queued.`);await load()}catch(value){setError(value instanceof Error?value.message:"Run could not be retried")}finally{setRetrying("")}}
  return <ProductShell title="Workflows" action={<button className="button button-dark" onClick={()=>setOpen(true)}><Plus size={16}/>New workflow</button>}>
    <section className="metric-grid compact-metrics"><article className="summary-card"><span>Active workflows</span><strong>{totals.active}</strong><small>Listening for events</small></article><article className="summary-card"><span>Recent runs</span><strong>{totals.runs}</strong><small>Visible execution history</small></article><article className="summary-card"><span>Failed runs</span><strong>{totals.failed}</strong><small>Available for review and retry</small></article></section>
    {error&&<p className="form-error">{error}</p>}{notice&&<p className="form-success">{notice}</p>}
    <section className="workflow-list">{flows===null?<article className="panel"><p>Loading workflows…</p></article>:flows.length===0?<article className="panel empty-state"><Workflow size={24}/><h3>No workflows yet</h3><p>Create an event-driven workflow with conditions, delays, contact updates and replies.</p></article>:flows.map((flow,index)=>{const version=flow.workflow_versions.slice().sort((a,b)=>b.version-a.version)[0];return <article className="panel workflow-record" key={flow.id}><header><span className={`avatar tone-${index%4}`}><Workflow size={16}/></span><div><h2>{flow.name}</h2><p>Version {version?.version??1} · {version?.graph.nodes.length??0} nodes · Updated {new Date(flow.updated_at).toLocaleString()}</p></div><span className={`status ${flow.status}`}>{flow.status}</span>{flow.status==="active"?<button className="button button-outline small" disabled><Check size={14}/>Active</button>:<button className="button button-outline small" onClick={()=>publish(flow)} disabled={Boolean(publishing)}>{publishing===flow.id?"Publishing…":"Publish"}</button>}</header><div className="node-strip">{version?.graph.nodes.map(node=><span key={node.id}><i/>{pretty(node.type)}</span>)}</div><section className="run-history"><h3>Execution history</h3>{!flow.workflow_runs?.length?<p>No runs yet. A published message trigger will create the first run.</p>:flow.workflow_runs.map(run=><div className="run-row" key={run.id}><span className={`run-dot ${run.status}`}/><span><strong>{pretty(run.status)} · Attempt {run.attempt}</strong><small>{new Date(run.started_at).toLocaleString()} · {run.workflow_run_steps?.length??0} recorded steps</small>{run.status==="failed"&&typeof run.state?.error==="string"&&<em>{run.state.error}</em>}</span>{run.current_node_id&&<code>{run.current_node_id}</code>}{run.status==="failed"&&<button className="button button-outline small" disabled={Boolean(retrying)} onClick={()=>retry(run)}>{retrying===run.id?"Queueing…":"Retry"}</button>}</div>)}</section></article>})}</section>
    {open&&<div className="modal-backdrop"><div className="modal workflow-modal"><div className="panel-head"><div><span className="eyebrow">Versioned automation</span><h2>Create workflow</h2></div><button className="icon-button" onClick={()=>setOpen(false)} aria-label="Close"><X size={16}/></button></div><form onSubmit={create}><div className="form-columns"><label>Workflow name<input required minLength={2} maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Keyword condition (optional)<input maxLength={120} value={keyword} onChange={e=>setKeyword(e.target.value)} placeholder="Example: price"/></label><label>Delay seconds<input type="number" min="0" max="2592000" value={delay} onChange={e=>setDelay(Number(e.target.value))}/></label><label>Update lifecycle<select value={stage} onChange={e=>setStage(e.target.value)}>{stages.map(item=><option key={item} value={item}>{item?pretty(item):"No change"}</option>)}</select></label></div><label>Internal note (optional)<input maxLength={4000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Example: Qualified automatically"/></label><label>Reply message<textarea required maxLength={4096} value={reply} onChange={e=>setReply(e.target.value)}/></label><div className="security-note"><Clock3 size={17}/><p>Keyword workflows hand unmatched conversations to a human. Drafts never run until published; each node is logged and idempotent.</p></div><button className="button button-dark full" disabled={busy}>{busy?"Creating…":"Create workflow draft"}</button></form></div></div>}
  </ProductShell>
}
