"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { MessageCircleMore,ShieldCheck } from "./icons";
import { apiData,loadWorkspace } from "@/lib/client-api";
type Reply={id:string;shortcut:string;title:string;body:string};type Sla={id:string;name:string;first_response_minutes:number;resolution_minutes:number};
export function OperationsSettings(){const[tenantId,setTenantId]=useState("");const[replies,setReplies]=useState<Reply[]>([]);const[sla,setSla]=useState<Sla|null>(null);const[shortcut,setShortcut]=useState("/");const[title,setTitle]=useState("");const[body,setBody]=useState("");const[slaName,setSlaName]=useState("Standard support");const[first,setFirst]=useState(15);const[resolution,setResolution]=useState(1440);const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[notice,setNotice]=useState("");
const load=useCallback(async()=>{const workspace=await loadWorkspace();if(!workspace.workspace)throw new Error("No active workspace");setTenantId(workspace.workspace.id);const[replyRows,slaRows]=await Promise.all([apiData<Reply[]>(`/api/v1/saved-replies?tenantId=${workspace.workspace.id}`),apiData<Sla[]>(`/api/v1/sla-policies?tenantId=${workspace.workspace.id}`)]);setReplies(replyRows);const current=slaRows[0]??null;setSla(current);if(current){setSlaName(current.name);setFirst(current.first_response_minutes);setResolution(current.resolution_minutes)}} ,[]);useEffect(()=>{load().catch((v)=>setError(v instanceof Error?v.message:"Settings could not be loaded"))},[load]);
async function saveReply(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{await apiData("/api/v1/saved-replies",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tenantId,shortcut,title,body})});setShortcut("/");setTitle("");setBody("");await load();setNotice("Saved reply is ready in Inbox")}catch(v){setError(v instanceof Error?v.message:"Reply could not be saved")}finally{setBusy(false)}}
async function saveSla(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{await apiData("/api/v1/sla-policies",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tenantId,name:slaName,firstResponseMinutes:first,resolutionMinutes:resolution})});await load();setNotice("SLA policy updated")}catch(v){setError(v instanceof Error?v.message:"SLA could not be saved")}finally{setBusy(false)}}
return <>{(error||notice)&&<p className={error?"form-error":"form-success"}>{error||notice}</p>}<section className="settings-grid"><article className="panel settings-card"><header><span className="soft-icon tone-0"><MessageCircleMore size={18}/></span><div><span className="eyebrow">Inbox productivity</span><h2>Saved replies</h2><p>Insert consistent answers without retyping.</p></div></header><div className="reply-list">{replies.length===0?<p>No saved replies yet.</p>:replies.map((reply)=><div key={reply.id}><code>{reply.shortcut}</code><span><strong>{reply.title}</strong><small>{reply.body}</small></span></div>)}</div><form onSubmit={saveReply}><label>Shortcut<input required pattern="/[a-z0-9_-]{2,30}" value={shortcut} onChange={(e)=>setShortcut(e.target.value.toLowerCase())} placeholder="/welcome"/></label><label>Title<input required minLength={2} maxLength={80} value={title} onChange={(e)=>setTitle(e.target.value)}/></label><label>Reply text<textarea required maxLength={4000} value={body} onChange={(e)=>setBody(e.target.value)}/></label><button className="button button-dark" disabled={busy}>Save reply</button></form></article><article className="panel settings-card"><header><span className="soft-icon tone-1"><ShieldCheck size={18}/></span><div><span className="eyebrow">Service target</span><h2>Default SLA</h2><p>Track response and resolution deadlines.</p></div></header>{sla&&<div className="sla-current"><strong>{sla.name}</strong><span>First response {sla.first_response_minutes} min · Resolve {sla.resolution_minutes} min</span></div>}<form onSubmit={saveSla}><label>Policy name<input required minLength={2} maxLength={80} value={slaName} onChange={(e)=>setSlaName(e.target.value)}/></label><label>First response minutes<input required type="number" min={1} max={10080} value={first} onChange={(e)=>setFirst(Number(e.target.value))}/></label><label>Resolution minutes<input required type="number" min={1} max={43200} value={resolution} onChange={(e)=>setResolution(Number(e.target.value))}/></label><button className="button button-dark" disabled={busy}>Save policy</button></form></article></section></>}
