"use client";
import{useEffect,useState}from"react";import{AlertTriangle,CheckCircle2,Clock3,RefreshCw,ShieldCheck}from"lucide-react";import{apiData,loadWorkspace}from"@/lib/client-api";
type Snapshot={capturedAt:string;worker:{status:string;startedAt:string;finishedAt:string|null;claimed:number;completed:number;failed:number;durationMs:number|null}|null;jobs:{queued:number;processing:number;retry:number;dead:number;completed24h:number;oldestReadySeconds:number|null};webhooks:{pending:number;processed24h:number;failed:number;quarantined:number};outbox:{unpublished:number;stale:number};messages:{unknown:number;failed:number};byKind:Record<string,{queued:number;processing:number;retry:number;dead:number}>};type Rule={id:string;metric:string;name:string;severity:string;threshold:number;window_minutes:number;enabled:boolean;updated_at:string};type Incident={id:string;metric:string;severity:string;observed_value:number;threshold:number;status:string;summary:string;first_seen_at:string;last_seen_at:string;acknowledged_at:string|null;resolved_at:string|null};type Data={snapshot:Snapshot;rules:Rule[];incidents:Incident[]};
const pretty=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,(letter)=>letter.toUpperCase());const age=(seconds:number|null)=>seconds==null?"No ready jobs":seconds<60?`${seconds}s old`:seconds<3600?`${Math.round(seconds/60)}m old`:`${Math.round(seconds/3600)}h old`;
export function OperationsWorkspace(){
 const[tenantId,setTenantId]=useState("");const[role,setRole]=useState("");const[data,setData]=useState<Data|null>(null);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[busy,setBusy]=useState(false);const canManage=role==="owner"||role==="manager";
 async function load(id=tenantId){if(!id)return;setError("");setData(await apiData<Data>(`/api/v1/operations?tenantId=${id}`))}
 useEffect(()=>{const controller=new AbortController();(async()=>{try{const workspace=await loadWorkspace(controller.signal);if(!workspace.workspace)throw new Error("No active workspace");setTenantId(workspace.workspace.id);setRole(workspace.workspace.role);setData(await apiData<Data>(`/api/v1/operations?tenantId=${workspace.workspace.id}`,{signal:controller.signal}))}catch(value){if(value instanceof Error&&value.name!=="AbortError")setError(value.message)}})();return()=>controller.abort()},[]);
 async function evaluate(){setBusy(true);setError("");setNotice("");try{setData(await apiData<Data>("/api/v1/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tenantId})}));setNotice("Health check completed from live queue data.")}catch(value){setError(value instanceof Error?value.message:"Health check failed")}finally{setBusy(false)}}
 async function setIncident(id:string,status:"acknowledged"|"resolved"){setBusy(true);setError("");try{await apiData(`/api/v1/operations/incidents/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({tenantId,status})});await load();setNotice(status==="acknowledged"?"Incident acknowledged.":"Incident resolved.")}catch(value){setError(value instanceof Error?value.message:"Update failed")}finally{setBusy(false)}}
 async function updateRule(rule:Rule,changes:Partial<Pick<Rule,"threshold"|"enabled">>){setBusy(true);setError("");try{await apiData(`/api/v1/operations/rules/${rule.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({tenantId,threshold:changes.threshold??rule.threshold,enabled:changes.enabled??rule.enabled})});await load();setNotice("Alert rule updated.")}catch(value){setError(value instanceof Error?value.message:"Update failed")}finally{setBusy(false)}}
 const open=data?.incidents.filter((item)=>item.status!=="resolved")??[];const healthy=Boolean(data)&&open.length===0&&data!.snapshot.jobs.dead===0&&data!.snapshot.webhooks.failed===0&&data!.snapshot.webhooks.quarantined===0&&data!.snapshot.outbox.stale===0;
 return <><section className="operations-hero panel"><div className={`operations-signal ${healthy?"healthy":"attention"}`}>{healthy?<CheckCircle2 size={22}/>:<AlertTriangle size={22}/>}</div><div><span className="eyebrow">Production control</span><h2>{data?(healthy?"Systems are operating normally":"Operations need attention"):"Reading system health…"}</h2><p>Live queue, Meta webhook, outbox and delivery safety signals for this workspace.</p></div>{canManage&&<button className="button button-dark" onClick={()=>void evaluate()} disabled={busy}><RefreshCw size={15}/>{busy?"Checking…":"Run health check"}</button>}</section>
 {error&&<p className="form-error">{error}</p>}{notice&&<p className="form-success">{notice}</p>}
 <section className="operations-metrics"><article><span>Worker</span><strong>{data?.snapshot.worker?.status??"No runs"}</strong><small>{data?.snapshot.worker?`${data.snapshot.worker.completed} completed · ${data.snapshot.worker.failed} failed`:"Waiting for next scheduled run"}</small></article><article><span>Ready jobs</span><strong>{(data?.snapshot.jobs.queued??0)+(data?.snapshot.jobs.retry??0)}</strong><small>{age(data?.snapshot.jobs.oldestReadySeconds??null)}</small></article><article><span>Dead jobs</span><strong>{data?.snapshot.jobs.dead??0}</strong><small>{data?.snapshot.jobs.completed24h??0} completed in 24h</small></article><article><span>Webhook failures</span><strong>{(data?.snapshot.webhooks.failed??0)+(data?.snapshot.webhooks.quarantined??0)}</strong><small>{data?.snapshot.webhooks.processed24h??0} processed in 24h</small></article><article><span>Stale outbox</span><strong>{data?.snapshot.outbox.stale??0}</strong><small>{data?.snapshot.outbox.unpublished??0} unpublished</small></article><article><span>Unknown delivery</span><strong>{data?.snapshot.messages.unknown??0}</strong><small>{data?.snapshot.messages.failed??0} failed in 24h</small></article></section>
 <section className="operations-grid"><article className="panel"><div className="panel-head"><div><span className="eyebrow">Queue</span><h2>Work by type</h2></div><Clock3 size={18}/></div><div className="operations-table"><div className="operations-row header"><span>Type</span><span>Queued</span><span>Working</span><span>Retry</span><span>Dead</span></div>{Object.entries(data?.snapshot.byKind??{}).length===0?<div className="empty-state compact"><CheckCircle2 size={21}/><h3>Queue is clear</h3><p>No jobs in the last 30 days need processing.</p></div>:Object.entries(data?.snapshot.byKind??{}).map(([kind,value])=><div className="operations-row" key={kind}><strong>{pretty(kind)}</strong><span>{value.queued}</span><span>{value.processing}</span><span>{value.retry}</span><span>{value.dead}</span></div>)}</div></article>
 <article className="panel"><div className="panel-head"><div><span className="eyebrow">Incidents</span><h2>Active alerts</h2></div><ShieldCheck size={18}/></div><div className="incident-list">{open.length===0?<div className="empty-state compact"><CheckCircle2 size={21}/><h3>No active incidents</h3><p>Run a health check to evaluate current values against alert rules.</p></div>:open.map(item=><article key={item.id} className={`incident ${item.severity}`}><header><strong>{pretty(item.metric)}</strong><span>{item.status}</span></header><p>{item.summary}</p><small>{item.observed_value} observed · threshold {item.threshold} · {new Date(item.last_seen_at).toLocaleString()}</small>{canManage&&<div>{item.status==="open"&&<button className="button small" onClick={()=>void setIncident(item.id,"acknowledged")} disabled={busy}>Acknowledge</button>}<button className="button small" onClick={()=>void setIncident(item.id,"resolved")} disabled={busy}>Resolve</button></div>}</article>)}</div></article></section>
 <section className="panel alert-rules"><div className="panel-head"><div><span className="eyebrow">Guardrails</span><h2>Alert rules</h2></div><small>Changes apply to the next health check.</small></div>{(data?.rules??[]).map(rule=><div className="alert-rule" key={rule.id}><span className={`rule-dot ${rule.severity}`}/><div><strong>{rule.name}</strong><small>{pretty(rule.metric)} · {rule.window_minutes} minute window</small></div><label>Threshold<input type="number" min={1} value={rule.threshold} disabled={!canManage||busy} onChange={(event)=>{const threshold=Math.max(1,Number(event.target.value));setData(current=>current?{...current,rules:current.rules.map(item=>item.id===rule.id?{...item,threshold}:item)}:current)}} onBlur={(event)=>void updateRule(rule,{threshold:Math.max(1,Number(event.currentTarget.value))})}/></label><label className="switch-label"><input type="checkbox" checked={rule.enabled} disabled={!canManage||busy} onChange={(event)=>void updateRule(rule,{enabled:event.target.checked})}/><span>{rule.enabled?"On":"Off"}</span></label></div>)}</section>
 {data&&<p className="analytics-note"><CheckCircle2 size={14}/>Snapshot captured {new Date(data.snapshot.capturedAt).toLocaleString()}. No sample health data is displayed.</p>}</>;
}
