"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { Plus, UsersRound, X } from "./icons";
import { apiData, loadWorkspace } from "@/lib/client-api";

type Team={id:string;name:string;capacity:number;created_at:string};type Member={user_id:string;role:string;status:string;email:string;display_name:string;team_ids:string[]};type Payload={teams:Team[];members:Member[]};
const initials=(value:string)=>value.split(/\s+/).map((part)=>part[0]).join("").slice(0,2).toUpperCase()||"PF";
export function TeamWorkspace(){const [tenantId,setTenantId]=useState("");const [data,setData]=useState<Payload>({teams:[],members:[]});const [selectedId,setSelectedId]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [open,setOpen]=useState(false);const [name,setName]=useState("");const [capacity,setCapacity]=useState(10);
  const load=useCallback(async()=>{setLoading(true);try{const workspace=await loadWorkspace();if(!workspace.workspace)throw new Error("No active workspace");setTenantId(workspace.workspace.id);const payload=await apiData<Payload>(`/api/v1/teams?tenantId=${workspace.workspace.id}`);setData(payload);setSelectedId((current)=>current||payload.teams[0]?.id||"");}finally{setLoading(false)}},[]);useEffect(()=>{load().catch((value)=>setError(value instanceof Error?value.message:"Team data could not be loaded"))},[load]);
  const selected=data.teams.find((team)=>team.id===selectedId)??null;const selectedMembers=useMemo(()=>data.members.filter((member)=>member.team_ids.includes(selectedId)),[data.members,selectedId]);
  async function createTeam(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const team=await apiData<Team>("/api/v1/teams",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tenantId,name,capacity})});setOpen(false);setName("");await load();setSelectedId(team.id);setNotice("Team created");}catch(value){setError(value instanceof Error?value.message:"Team creation failed")}finally{setBusy(false)}}
  async function toggleMember(userId:string){if(!selected)return;setBusy(true);setError("");const memberIds=selectedMembers.some((member)=>member.user_id===userId)?selectedMembers.filter((member)=>member.user_id!==userId).map((member)=>member.user_id):[...selectedMembers.map((member)=>member.user_id),userId];try{await apiData(`/api/v1/teams/${selected.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({tenantId,memberIds})});await load();setNotice("Team membership updated");}catch(value){setError(value instanceof Error?value.message:"Membership update failed")}finally{setBusy(false)}}
  return <><div className="team-summary"><article className="panel"><span>Active members</span><strong>{data.members.filter((m)=>m.status==="active").length}</strong><small>Across this workspace</small></article><article className="panel"><span>Teams</span><strong>{data.teams.length}</strong><small>Routing groups</small></article><article className="panel"><span>Available capacity</span><strong>{data.teams.reduce((sum,team)=>sum+team.capacity,0)}</strong><small>Total configured seats</small></article></div><section className="team-workspace panel"><aside className="team-list"><header><div><span className="eyebrow">Routing groups</span><h2>Teams</h2></div><button className="icon-button" onClick={()=>setOpen(true)}><Plus size={16}/></button></header>{loading?<p className="directory-empty">Loading teams…</p>:data.teams.length===0?<div className="empty-state"><UsersRound size={24}/><h3>Create your first team</h3><p>Group agents for sales, support or order operations.</p></div>:data.teams.map((team)=><button key={team.id} className={team.id===selectedId?"active":""} onClick={()=>setSelectedId(team.id)}><span className="soft-icon tone-0"><UsersRound size={16}/></span><span><strong>{team.name}</strong><small>{data.members.filter((member)=>member.team_ids.includes(team.id)).length} of {team.capacity} members</small></span></button>)}</aside><main className="team-detail">{!selected?<div className="empty-state"><UsersRound size={26}/><h3>No team selected</h3><p>Create a routing team to assign conversations consistently.</p></div>:<><header><div><span className="eyebrow">Team members</span><h2>{selected.name}</h2><p>{selectedMembers.length} members · capacity {selected.capacity}</p></div><span className="status running">Active</span></header>{error&&<p className="form-error">{error}</p>}{notice&&<p className="form-success">{notice}</p>}<div className="member-list">{data.members.map((member)=><label key={member.user_id}><span className="avatar small">{initials(member.display_name)}</span><span><strong>{member.display_name}</strong><small>{member.email} · {member.role}</small></span><input type="checkbox" checked={member.team_ids.includes(selected.id)} disabled={busy} onChange={()=>toggleMember(member.user_id)}/></label>)}</div></>}</main></section>{open&&<div className="modal-backdrop"><div className="modal"><div className="panel-head"><div><span className="eyebrow">Routing group</span><h2>Create team</h2></div><button className="icon-button" onClick={()=>setOpen(false)}><X size={16}/></button></div><form onSubmit={createTeam}><label>Team name<input required minLength={2} maxLength={80} value={name} onChange={(e)=>setName(e.target.value)} placeholder="Example: Sales"/></label><label>Capacity<input required type="number" min="1" max="1000" value={capacity} onChange={(e)=>setCapacity(Number(e.target.value))}/></label><button className="button button-dark full" disabled={busy}>{busy?"Creating…":"Create team"}</button></form></div></div>}</>}
