"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { ProductShell } from "@/components/product-shell";
import { CalendarClock, Plus, X } from "@/components/icons";
import { apiData, loadWorkspace, type WorkspaceData } from "@/lib/client-api";

type Contact={id:string;display_name:string|null;phone_e164:string;wa_id:string};
type Schedule={id:string;contact_id:string;content:{text?:string};due_at:string;expires_at:string;status:string;created_at:string};
export default function SchedulesPage(){
 const [workspace,setWorkspace]=useState<WorkspaceData|null>(null);const [contacts,setContacts]=useState<Contact[]>([]);const [rows,setRows]=useState<Schedule[]|null>(null);const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [contactId,setContactId]=useState("");const [message,setMessage]=useState("");const [dueAt,setDueAt]=useState("");
 const load=useCallback(async(signal?:AbortSignal)=>{const ws=await loadWorkspace(signal);if(!ws.workspace)throw new Error("No active workspace is available");setWorkspace(ws);const [scheduled,people]=await Promise.all([apiData<Schedule[]>(`/api/v1/schedules?tenantId=${ws.workspace.id}`,{signal}),apiData<Contact[]>(`/api/v1/contacts?tenantId=${ws.workspace.id}`,{signal})]);setRows(scheduled);setContacts(people);setContactId(current=>current||people[0]?.id||"");},[]);
 useEffect(()=>{const controller=new AbortController();load(controller.signal).catch(value=>{if(value instanceof Error&&value.name!=="AbortError")setError(value.message)});return()=>controller.abort()},[load]);
 async function create(event:FormEvent){event.preventDefault();if(!workspace?.workspace||!workspace.channels[0])return;setBusy(true);setError("");try{const due=new Date(dueAt);await apiData("/api/v1/schedules",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tenantId:workspace.workspace.id,channelId:workspace.channels[0].id,contactId,content:{type:"text",text:message},dueAt:due.toISOString(),expiresAt:new Date(due.getTime()+24*60*60_000).toISOString(),idempotencyKey:crypto.randomUUID()})});setOpen(false);setMessage("");setDueAt("");await load();}catch(value){setError(value instanceof Error?value.message:"Schedule could not be created")}finally{setBusy(false)}}
 const ready=Boolean(workspace?.channels.some(channel=>channel.status==="active")&&contacts.length);
 return <ProductShell title="Schedules" action={<button className="button button-dark" disabled={!ready} onClick={()=>setOpen(true)}><Plus size={16}/>Schedule message</button>}>{error&&<p className="form-error">{error}</p>}<section className="module-intro panel"><span className="soft-icon tone-0"><CalendarClock size={22}/></span><div><span className="eyebrow">Durable reminders</span><h2>Messages are stored with an expiry and dispatched by the bounded worker.</h2></div></section><section className="panel data-panel">{rows===null?<p>Loading schedules…</p>:rows.length===0?<div className="empty-state"><CalendarClock size={22}/><h3>No scheduled messages</h3><p>Add a contact and create a one-off reminder. Dispatch remains subject to consent and the live-send switch.</p></div>:<div className="data-table"><div className="data-row header"><span>Message</span><span>Status</span><span>Contact</span><span>Due</span><span>Expires</span><span/></div>{rows.map(row=><div className="data-row" key={row.id}><span><i className="campaign-icon"><CalendarClock size={17}/></i><strong>{row.content?.text??"Scheduled message"}</strong><small>Created {new Date(row.created_at).toLocaleString()}</small></span><span><b className={`status ${row.status}`}>{row.status}</b></span><span>{contacts.find(person=>person.id===row.contact_id)?.display_name??"Contact"}</span><span>{new Date(row.due_at).toLocaleString()}</span><span>{new Date(row.expires_at).toLocaleString()}</span><span/></div>)}</div>}</section>{open&&<div className="modal-backdrop"><div className="modal"><div className="panel-head"><div><span className="eyebrow">One-off reminder</span><h2>Schedule message</h2></div><button className="icon-button" onClick={()=>setOpen(false)} aria-label="Close"><X size={16}/></button></div><form onSubmit={create}><label>Contact<select required value={contactId} onChange={event=>setContactId(event.target.value)}>{contacts.map(person=><option key={person.id} value={person.id}>{person.display_name||person.phone_e164||person.wa_id}</option>)}</select></label><label>Message<textarea required maxLength={4096} value={message} onChange={event=>setMessage(event.target.value)}/></label><label>Send at<input type="datetime-local" required value={dueAt} onChange={event=>setDueAt(event.target.value)}/></label><small>The message expires 24 hours after its scheduled time and is blocked if the contact opts out.</small><button className="button button-dark full" disabled={busy}>{busy?"Saving…":"Save schedule"}</button></form></div></div>}</ProductShell>
}
