"use client";

import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { ProductShell } from "@/components/product-shell";
import { CalendarClock,Plus,SendHorizontal,X } from "@/components/icons";
import { apiData,loadWorkspace,type WorkspaceData } from "@/lib/client-api";

type Tag={id:string;name:string;color:string};
type Audience={eligible:number;excluded:number;opted_out?:number;suppressed?:number;filter_mismatch?:number};
type Campaign={id:string;name:string;status:string;channel_id:string;template:{name?:string;language?:string};audience_filter:{lifecycleStages?:string[];tagIds?:string[];minLeadScore?:number;source?:string};audience_preview:Audience;delivery:Record<string,number>;scheduled_at:string|null;created_at:string;updated_at:string};
const stages=["lead","qualified","opportunity","customer","repeat_customer","win_back","inactive"];
const pretty=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,(v)=>v.toUpperCase());

export default function CampaignsPage(){
  const[workspace,setWorkspace]=useState<WorkspaceData|null>(null);const[campaigns,setCampaigns]=useState<Campaign[]|null>(null);const[tags,setTags]=useState<Tag[]>([]);const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[actionId,setActionId]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");const[name,setName]=useState("");const[template,setTemplate]=useState("hello_world");const[language,setLanguage]=useState("en_US");const[scheduled,setScheduled]=useState("");const[selectedStages,setSelectedStages]=useState<string[]>([]);const[selectedTags,setSelectedTags]=useState<string[]>([]);const[minScore,setMinScore]=useState(0);const[source,setSource]=useState("");
  const load=useCallback(async(signal?:AbortSignal)=>{const ws=await loadWorkspace(signal);if(!ws.workspace)throw new Error("No active workspace is available");setWorkspace(ws);const[rows,tagRows]=await Promise.all([apiData<Campaign[]>(`/api/v1/campaigns?tenantId=${ws.workspace.id}`,{signal}),apiData<Tag[]>(`/api/v1/tags?tenantId=${ws.workspace.id}`,{signal})]);setCampaigns(rows);setTags(tagRows)},[]);
  useEffect(()=>{const controller=new AbortController();load(controller.signal).catch(value=>{if(value instanceof Error&&value.name!=="AbortError")setError(value.message)});return()=>controller.abort()},[load]);
  const counts=useMemo(()=>({draft:campaigns?.filter(row=>row.status==="draft").length??0,active:campaigns?.filter(row=>["scheduled","running"].includes(row.status)).length??0,completed:campaigns?.filter(row=>row.status==="completed").length??0}),[campaigns]);
  async function create(event:FormEvent){event.preventDefault();if(!workspace?.workspace||!workspace.channels[0])return;setBusy(true);setError("");setNotice("");try{await apiData("/api/v1/campaigns",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({tenantId:workspace.workspace.id,name,channelId:workspace.channels[0].id,template:{type:"template",name:template,language},audienceFilter:{lifecycleStages:selectedStages,tagIds:selectedTags,minLeadScore:minScore,...(source.trim()?{source:source.trim()}: {})},...(scheduled?{scheduledAt:new Date(scheduled).toISOString()}:{})})});setOpen(false);setName("");setScheduled("");setSelectedStages([]);setSelectedTags([]);setMinScore(0);setSource("");setNotice(scheduled?"Campaign scheduled. Audience is revalidated at send time.":"Campaign draft created with a live audience preview.");await load()}catch(value){setError(value instanceof Error?value.message:"Campaign could not be created")}finally{setBusy(false)}}
  async function launch(campaign:Campaign){if(!window.confirm(`Launch “${campaign.name}” for ${campaign.audience_preview.eligible} eligible contact(s)? Consent and suppression will be checked again before every send.`))return;setActionId(campaign.id);setError("");setNotice("");try{const result=await apiData<{recipientCount:number}>(`/api/v1/campaigns/${campaign.id}/launch`,{method:"POST"});setNotice(`Campaign launched for ${result.recipientCount} eligible contact${result.recipientCount===1?"":"s"}.`);await load()}catch(value){setError(value instanceof Error?value.message:"Campaign could not be launched")}finally{setActionId("")}}
  const channelReady=Boolean(workspace?.channels.some(channel=>channel.status==="active"));
  return <ProductShell title="Campaigns" action={<button className="button button-dark" onClick={()=>setOpen(true)} disabled={!channelReady}><Plus size={16}/>New campaign</button>}>
    <section className="metric-grid compact-metrics"><article className="summary-card"><span>Drafts</span><strong>{counts.draft}</strong><small>Audience preview ready</small></article><article className="summary-card"><span>Active</span><strong>{counts.active}</strong><small>Scheduled or sending</small></article><article className="summary-card"><span>Completed</span><strong>{counts.completed}</strong><small>Finished runs</small></article></section>
    {error&&<p className="form-error">{error}</p>}{notice&&<p className="form-success">{notice}</p>}
    <section className="panel data-panel"><div className="table-toolbar"><div><span className="eyebrow">Official WhatsApp</span><h2>Campaign drafts and runs</h2></div></div>{campaigns===null?<p className="muted">Loading campaigns…</p>:campaigns.length===0?<div className="empty-state"><CalendarClock size={22}/><h3>No campaigns yet</h3><p>Create an approved-template campaign with a consent-safe audience.</p></div>:<div className="data-table campaign-table"><div className="data-row header"><span>Campaign</span><span>Status</span><span>Audience</span><span>Template</span><span>Schedule</span><span>Action</span></div>{campaigns.map((row,index)=><div className="data-row" key={row.id}><span><i className={`campaign-icon tone-${index%4}`}><CalendarClock size={17}/></i><strong>{row.name}</strong><small>{row.audience_filter.lifecycleStages?.length?row.audience_filter.lifecycleStages.map(pretty).join(", "):"All lifecycle stages"}</small></span><span><b className={`status ${row.status}`}>{row.status}</b></span><span className="audience-count"><strong>{row.audience_preview.eligible}</strong><small>eligible · {row.audience_preview.excluded} excluded</small></span><span>{row.template?.name??"—"}<small>{row.template?.language??"—"}</small></span><span>{row.scheduled_at?new Date(row.scheduled_at).toLocaleString():"Manual launch"}</span><span>{row.status==="draft"?<button className="button button-outline small" onClick={()=>launch(row)} disabled={Boolean(actionId)||row.audience_preview.eligible===0}><SendHorizontal size={14}/>{actionId===row.id?"Launching…":"Launch"}</button>:<small>{row.status==="scheduled"?"Automatic":`${row.delivery.delivered??0} delivered`}</small>}</span></div>)}</div>}</section>
    {open&&<div className="modal-backdrop"><div className="modal campaign-modal"><div className="panel-head"><div><span className="eyebrow">Approved template</span><h2>Create campaign</h2></div><button className="icon-button" onClick={()=>setOpen(false)} aria-label="Close"><X size={16}/></button></div><form onSubmit={create}><div className="form-columns"><label>Campaign name<input required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>Meta template<input required value={template} onChange={e=>setTemplate(e.target.value)}/></label><label>Language<input required value={language} onChange={e=>setLanguage(e.target.value)}/></label><label>Schedule (optional)<input type="datetime-local" value={scheduled} onChange={e=>setScheduled(e.target.value)}/></label></div><fieldset><legend>Lifecycle stages</legend><div className="choice-grid">{stages.map(stage=><label key={stage}><input type="checkbox" checked={selectedStages.includes(stage)} onChange={()=>setSelectedStages(items=>items.includes(stage)?items.filter(item=>item!==stage):[...items,stage])}/>{pretty(stage)}</label>)}</div></fieldset>{tags.length>0&&<fieldset><legend>Contact tags</legend><div className="choice-grid">{tags.map(tag=><label key={tag.id}><input type="checkbox" checked={selectedTags.includes(tag.id)} onChange={()=>setSelectedTags(items=>items.includes(tag.id)?items.filter(item=>item!==tag.id):[...items,tag.id])}/>{tag.name}</label>)}</div></fieldset>}<div className="form-columns"><label>Minimum lead score<input type="number" min="0" max="100" value={minScore} onChange={e=>setMinScore(Number(e.target.value))}/></label><label>Exact source (optional)<input maxLength={80} value={source} onChange={e=>setSource(e.target.value)}/></label></div><small>Only opted-in, unsuppressed contacts matching this audience are snapshotted. Eligibility is checked again before every send.</small><button className="button button-dark full" disabled={busy}>{busy?"Creating…":scheduled?"Schedule campaign":"Create draft"}</button></form></div></div>}
  </ProductShell>
}
