"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ProductShell, StatCard } from "@/components/product-shell";
import { ArrowUpRight, Check, MessageCircleMore } from "@/components/icons";
import { apiData, loadWorkspace } from "@/lib/client-api";

type Summary = { contacts: number; openConversations: number; outbound: number; delivered: number; failedOrUnknown: number; deliveryRate: number | null };
type InboxRow = { id: string; status: string; last_message_at: string | null; contacts: { display_name: string | null; wa_id: string } | Array<{ display_name: string | null; wa_id: string }>; messages: Array<{ content: Record<string, unknown> }> };
type Workflow = { id: string; name: string; status: string; active_version: number | null; updated_at: string };

function contact(row: InboxRow) { return Array.isArray(row.contacts) ? row.contacts[0] : row.contacts; }
function text(row: InboxRow) { const value=row.messages?.[0]?.content?.text; return typeof value === "string" ? value : "WhatsApp conversation"; }
function initials(value: string) { return value.split(/\s+/).filter(Boolean).map((part)=>part[0]).join("").slice(0,2).toUpperCase() || "WA"; }

export default function OverviewPage(){
  const [summary,setSummary]=useState<Summary|null>(null); const [inbox,setInbox]=useState<InboxRow[]>([]); const [workflows,setWorkflows]=useState<Workflow[]>([]); const [error,setError]=useState("");
  useEffect(()=>{const controller=new AbortController();(async()=>{try{const workspace=await loadWorkspace(controller.signal);if(!workspace.workspace)throw new Error("No active workspace is available");const tenantId=workspace.workspace.id;const [stats,rows,flows]=await Promise.all([apiData<Summary>(`/api/v1/analytics/summary?tenantId=${tenantId}`,{signal:controller.signal}),apiData<InboxRow[]>(`/api/v1/inbox?tenantId=${tenantId}`,{signal:controller.signal}),apiData<Workflow[]>(`/api/v1/workflows?tenantId=${tenantId}`,{signal:controller.signal})]);setSummary(stats);setInbox(rows.slice(0,5));setWorkflows(flows.slice(0,4));}catch(value){if(value instanceof Error&&value.name!=="AbortError")setError(value.message)}})();return()=>controller.abort()},[]);
  return <ProductShell title="Overview" action={<Link className="button button-dark" href="/app/inbox"><MessageCircleMore size={16}/>Open inbox</Link>}>
    {error&&<p className="form-error">{error}</p>}
    <section className="metric-grid"><StatCard label="Open conversations" value={summary?String(summary.openConversations):"—"} change="Live"/><StatCard label="Contacts" value={summary?String(summary.contacts):"—"} change="Live" tone="blue"/><StatCard label="Outbound messages" value={summary?String(summary.outbound):"—"} change="Total" tone="violet"/><StatCard label="Delivery rate" value={summary?.deliveryRate==null?"—":`${summary.deliveryRate}%`} change={summary?`${summary.delivered} delivered`:"Loading"} tone="amber"/></section>
    <section className="dashboard-grid"><article className="panel"><div className="panel-head"><div><span className="eyebrow">Shared inbox</span><h2>Recent conversations</h2></div><Link className="icon-button" href="/app/inbox"><ArrowUpRight size={17}/></Link></div>{inbox.length===0?<p className="muted">No conversations yet.</p>:inbox.map((row,index)=>{const person=contact(row);const name=person?.display_name||person?.wa_id||"WhatsApp contact";return <div className="attention-row" key={row.id}><span className={`avatar tone-${index%4}`}>{initials(name)}</span><div><strong>{name}</strong><small>{text(row)}</small></div><time>{row.last_message_at?new Date(row.last_message_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}):""}</time></div>})}</article><article className="panel"><div className="panel-head"><div><span className="eyebrow">Delivery health</span><h2>Official API activity</h2></div></div><div className="resolution"><div className="donut" style={{background:`conic-gradient(#54b57f 0 ${summary?.deliveryRate??0}%,#edf1ef ${summary?.deliveryRate??0}% 100%)`}}><span>{summary?.deliveryRate??0}%<small>delivered</small></span></div><div><p><i className="legend ai"/>Delivered <strong>{summary?.delivered??0}</strong></p><p><i className="legend human"/>Failed / unknown <strong>{summary?.failedOrUnknown??0}</strong></p><p><i className="legend open"/>Outbound <strong>{summary?.outbound??0}</strong></p></div></div></article></section>
    <section className="lower-grid"><article className="panel"><div className="panel-head"><div><span className="eyebrow">Automation</span><h2>Saved workflows</h2></div><Link className="text-link strong" href="/app/workflows">View all</Link></div>{workflows.length===0?<p className="muted">No workflows configured.</p>:workflows.map((flow)=><div className="workflow-list-row" key={flow.id}><span className="soft-icon tone-0"><Check size={18}/></span><div><strong>{flow.name}</strong><small>Updated {new Date(flow.updated_at).toLocaleDateString()}</small></div><span className={`status ${flow.status}`}>{flow.status}</span></div>)}</article><article className="panel"><div className="panel-head"><div><span className="eyebrow">System state</span><h2>Pilot activity</h2></div></div><div className="workflow-list-row"><span className="soft-icon tone-0"><Check size={18}/></span><div><strong>Signed Meta webhook</strong><small>Inbound messages use the durable worker</small></div><span className="status running">Active</span></div><div className="workflow-list-row"><span className="soft-icon tone-1"><Check size={18}/></span><div><strong>Tenant isolation</strong><small>Row-level security is enabled</small></div><span className="status running">Verified</span></div></article></section>
  </ProductShell>
}
