import { z } from "zod";
import { commerceConnectionSchema } from "@passion-fruit/contracts";
import { failure,ok,readJson,requestId } from "@/server/http";
import { requireTenantRole } from "@/server/supabase";

const querySchema=z.object({tenantId:z.uuid()});
export async function GET(request:Request){const id=requestId(request);try{const input=querySchema.parse(Object.fromEntries(new URL(request.url).searchParams));const{client}=await requireTenantRole(request,input.tenantId,["owner","manager","agent","analyst"]);const[{data:connections,error:connectionError},{data:products,error:productError},{data:variants,error:variantError},{data:orders,error:orderError}]=await Promise.all([client.from("integration_connections").select("id,category,provider,name,status,base_url,last_sync_at,last_error,created_at").eq("tenant_id",input.tenantId).order("created_at",{ascending:false}),client.from("commerce_products").select("id,connection_id,external_id,title,handle,status,image_url,updated_at").eq("tenant_id",input.tenantId).order("updated_at",{ascending:false}).limit(100),client.from("commerce_variants").select("id,product_id,sku,title,price_minor,currency,inventory_quantity,available").eq("tenant_id",input.tenantId).limit(200),client.from("commerce_orders").select("id,connection_id,external_id,order_number,customer_name,currency,total_minor,financial_status,fulfillment_status,placed_at").eq("tenant_id",input.tenantId).order("placed_at",{ascending:false}).limit(100)]);if(connectionError||productError||variantError||orderError)throw connectionError??productError??variantError??orderError;return ok({connections:connections??[],products:(products??[]).map(product=>({...product,variants:(variants??[]).filter(variant=>variant.product_id===product.id)})),orders:orders??[],summary:{stores:(connections??[]).filter(connection=>connection.category==="store").length,products:(products??[]).length,orders:(orders??[]).length,revenueMinor:(orders??[]).filter(order=>order.financial_status==="paid").reduce((total,order)=>total+Number(order.total_minor),0)}},id)}catch(error){return failure(error,id)}}

export async function POST(request:Request){const id=requestId(request);try{const input=commerceConnectionSchema.parse(await readJson(request));const{client,user}=await requireTenantRole(request,input.tenantId,["owner","manager"]);const{data,error}=await client.from("integration_connections").insert({tenant_id:input.tenantId,category:input.category,provider:input.provider,name:input.name,status:input.sandbox?"sandbox":"setup_required",base_url:input.baseUrl??null,scopes:[],created_by:user.id}).select("id,category,provider,name,status,base_url,last_sync_at,last_error,created_at").single();if(error)throw error;return ok(data,id,201)}catch(error){return failure(error,id)}}
