begin;
create table public.campaign_policies(
 tenant_id uuid primary key references public.tenants(id) on delete cascade,
 recipient_cap integer not null default 100 check(recipient_cap between 1 and 1000),
 daily_launch_limit integer not null default 5 check(daily_launch_limit between 1 and 100),
 approval_required boolean not null default true,
 updated_by uuid references auth.users(id) on delete set null,
 updated_at timestamptz not null default now()
);
insert into public.campaign_policies(tenant_id) select id from public.tenants on conflict do nothing;
alter table public.campaigns add column approval_status text not null default 'not_requested' check(approval_status in('not_requested','pending','approved','rejected')),add column recipient_cap integer not null default 100 check(recipient_cap between 1 and 1000),add column approval_requested_at timestamptz,add column approved_at timestamptz,add column approved_by uuid references auth.users(id) on delete set null;
update public.campaigns set approval_status='approved',approved_at=now() where status in('scheduled','running','completed');
create table public.campaign_approval_events(
 id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,campaign_id uuid not null,action text not null check(action in('requested','approved','rejected','paused','cancelled')),reason text,actor_id uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),foreign key(campaign_id,tenant_id) references public.campaigns(id,tenant_id) on delete cascade
);
create index campaign_approval_events_idx on public.campaign_approval_events(tenant_id,campaign_id,created_at desc);
alter table public.campaign_policies enable row level security;alter table public.campaign_approval_events enable row level security;
create policy campaign_policy_member_read on public.campaign_policies for select to authenticated using(public.is_tenant_member(tenant_id));create policy campaign_policy_owner_write on public.campaign_policies for all to authenticated using(public.has_tenant_role(tenant_id,array['owner'])) with check(public.has_tenant_role(tenant_id,array['owner']));
create policy campaign_approval_member_read on public.campaign_approval_events for select to authenticated using(public.is_tenant_member(tenant_id));
grant select,insert,update on public.campaign_policies to authenticated;grant select on public.campaign_approval_events to authenticated;

create or replace function public.request_campaign_approval(p_campaign_id uuid) returns integer language plpgsql security definer set search_path=public,pg_temp as $$
declare v_campaign public.campaigns%rowtype;v_policy public.campaign_policies%rowtype;v_eligible integer;
begin select * into v_campaign from public.campaigns where id=p_campaign_id for update;if v_campaign.id is null then raise exception 'campaign_not_found' using errcode='P0002';end if;if not public.has_tenant_role(v_campaign.tenant_id,array['owner','manager']) then raise exception 'tenant_access_denied' using errcode='42501';end if;if v_campaign.status not in('draft','paused') then raise exception 'campaign_not_reviewable' using errcode='22023';end if;select * into v_policy from public.campaign_policies where tenant_id=v_campaign.tenant_id;select count(*) into v_eligible from public.contacts c where c.tenant_id=v_campaign.tenant_id and public.contact_matches_audience(c.id,c.tenant_id,v_campaign.audience_filter);if v_eligible=0 then raise exception 'campaign_has_no_eligible_recipients' using errcode='P0002';end if;if v_eligible>v_policy.recipient_cap then raise exception 'campaign_recipient_cap_exceeded' using errcode='22023';end if;update public.campaigns set approval_status='pending',recipient_cap=v_policy.recipient_cap,approval_requested_at=now(),approved_at=null,approved_by=null,eligible_count=v_eligible,updated_at=now() where id=v_campaign.id;insert into public.campaign_approval_events(tenant_id,campaign_id,action,actor_id) values(v_campaign.tenant_id,v_campaign.id,'requested',auth.uid());return v_eligible;end;$$;
create or replace function public.review_campaign_approval(p_campaign_id uuid,p_decision text,p_reason text default null) returns text language plpgsql security definer set search_path=public,pg_temp as $$
declare v_campaign public.campaigns%rowtype;v_status text;
begin if p_decision not in('approved','rejected') then raise exception 'invalid_decision' using errcode='22023';end if;select * into v_campaign from public.campaigns where id=p_campaign_id for update;if v_campaign.id is null then raise exception 'campaign_not_found' using errcode='P0002';end if;if not public.has_tenant_role(v_campaign.tenant_id,array['owner','manager']) then raise exception 'tenant_access_denied' using errcode='42501';end if;if v_campaign.approval_status<>'pending' then raise exception 'campaign_not_pending_approval' using errcode='22023';end if;v_status:=case when p_decision='approved' and v_campaign.scheduled_at is not null and v_campaign.scheduled_at>now() then 'scheduled' else v_campaign.status end;update public.campaigns set approval_status=p_decision,approved_at=case when p_decision='approved' then now() else null end,approved_by=case when p_decision='approved' then auth.uid() else null end,status=case when p_decision='rejected' then 'draft' else v_status end,updated_at=now() where id=v_campaign.id;insert into public.campaign_approval_events(tenant_id,campaign_id,action,reason,actor_id) values(v_campaign.tenant_id,v_campaign.id,p_decision,p_reason,auth.uid());return p_decision;end;$$;
create or replace function public.control_campaign(p_campaign_id uuid,p_action text) returns text language plpgsql security definer set search_path=public,pg_temp as $$
declare v_campaign public.campaigns%rowtype;v_status text;
begin if p_action not in('paused','cancelled') then raise exception 'invalid_action' using errcode='22023';end if;select * into v_campaign from public.campaigns where id=p_campaign_id for update;if v_campaign.id is null then raise exception 'campaign_not_found' using errcode='P0002';end if;if not public.has_tenant_role(v_campaign.tenant_id,array['owner','manager']) then raise exception 'tenant_access_denied' using errcode='42501';end if;if p_action='paused' and v_campaign.status not in('running','scheduled') then raise exception 'campaign_not_pauseable' using errcode='22023';end if;if p_action='cancelled' and v_campaign.status in('completed','cancelled') then raise exception 'campaign_not_cancellable' using errcode='22023';end if;v_status:=p_action;update public.campaigns set status=v_status,updated_at=now() where id=v_campaign.id;insert into public.campaign_approval_events(tenant_id,campaign_id,action,actor_id) values(v_campaign.tenant_id,v_campaign.id,p_action,auth.uid());return v_status;end;$$;
revoke all on function public.request_campaign_approval(uuid),public.review_campaign_approval(uuid,text,text),public.control_campaign(uuid,text) from public,anon;grant execute on function public.request_campaign_approval(uuid),public.review_campaign_approval(uuid,text,text),public.control_campaign(uuid,text) to authenticated;

create or replace function public.launch_campaign(p_campaign_id uuid,p_max_recipients integer default 100) returns integer language plpgsql security definer set search_path=public,pg_temp as $$
declare v_campaign public.campaigns%rowtype;v_policy public.campaign_policies%rowtype;v_count integer;v_excluded integer;v_job_id uuid;v_launches integer;
begin select * into v_campaign from public.campaigns where id=p_campaign_id for update;if v_campaign.id is null then raise exception 'campaign_not_found' using errcode='P0002';end if;if not public.has_tenant_role(v_campaign.tenant_id,array['owner','manager']) then raise exception 'tenant_access_denied' using errcode='42501';end if;if not public.feature_enabled(v_campaign.tenant_id,'campaigns') then raise exception 'feature_disabled' using errcode='42501';end if;if v_campaign.approval_status<>'approved' then raise exception 'campaign_approval_required' using errcode='42501';end if;if v_campaign.status not in('draft','paused') then raise exception 'campaign_not_launchable' using errcode='22023';end if;select * into v_policy from public.campaign_policies where tenant_id=v_campaign.tenant_id;select count(*) into v_launches from public.usage_ledger where tenant_id=v_campaign.tenant_id and meter='campaign_launch' and occurred_at>=date_trunc('day',now());if v_launches>=v_policy.daily_launch_limit then raise exception 'campaign_daily_launch_limit_reached' using errcode='22023';end if;insert into public.campaign_recipients(campaign_id,tenant_id,contact_id) select v_campaign.id,v_campaign.tenant_id,c.id from public.contacts c where c.tenant_id=v_campaign.tenant_id and public.contact_matches_audience(c.id,c.tenant_id,v_campaign.audience_filter) order by c.created_at limit least(greatest(1,p_max_recipients),v_campaign.recipient_cap,v_policy.recipient_cap) on conflict do nothing;select count(*) into v_count from public.campaign_recipients where campaign_id=v_campaign.id and status='pending';select count(*)-v_count into v_excluded from public.contacts where tenant_id=v_campaign.tenant_id;if v_count=0 then raise exception 'campaign_has_no_eligible_recipients' using errcode='P0002';end if;update public.campaigns set status='running',audience_snapshot_at=now(),eligible_count=v_count,excluded_count=greatest(v_excluded,0),updated_at=now() where id=v_campaign.id;insert into public.usage_ledger(tenant_id,meter,logical_key,quantity,metadata) values(v_campaign.tenant_id,'campaign_launch',v_campaign.id::text,1,jsonb_build_object('recipientCount',v_count)) on conflict do nothing;insert into public.jobs(tenant_id,kind,payload) values(v_campaign.tenant_id,'campaign',jsonb_build_object('campaign_id',v_campaign.id)) returning id into v_job_id;insert into public.outbox(tenant_id,topic,payload) values(v_campaign.tenant_id,'job.campaign',jsonb_build_object('job_id',v_job_id,'kind','campaign'));return v_count;end;$$;
revoke all on function public.launch_campaign(uuid,integer) from public,anon;grant execute on function public.launch_campaign(uuid,integer) to authenticated;
commit;
