import { z } from "zod";
import { failure,ok,readJson,requestId } from "@/server/http";
import { ApiAuthError,requireUser } from "@/server/supabase";
const schema=z.object({tenantId:z.uuid(),prompt:z.string().trim().min(1).max(4000)});
const sensitive=/\b(refund|complaint|lawyer|legal|medical|emergency|human|person|agent)\b/i;
function confidence(prompt:string,content:string){const words=new Set(prompt.toLowerCase().match(/[a-z0-9]{3,}/g)??[]);if(!words.size)return 0;const haystack=content.toLowerCase();let matches=0;for(const word of words)if(haystack.includes(word))matches++;return Math.min(.98,.35+matches/words.size*.63)}
export async function POST(request:Request,context:{params:Promise<{agentId:string}>}){const id=requestId(request);try{const{agentId}=await context.params;z.uuid().parse(agentId);const input=schema.parse(await readJson(request));const{client,user}=await requireUser(request);const{data:agent,error:agentError}=await client.from("ai_agents").select("id,confidence_threshold,guardrails,mode").eq("id",agentId).eq("tenant_id",input.tenantId).maybeSingle();if(agentError)throw agentError;if(!agent)throw new ApiAuthError("agent_not_found",404);const guardrails=agent.guardrails as {handoffOnSensitiveIntent?:boolean;handoffOnMissingSource?:boolean;prohibitedTopics?:string[]};let outcome:"suggested"|"handoff"|"blocked"="suggested";let handoffReason:string|null=null;let response:string|null=null;let score=0;let citations:Array<{chunk_id:string;source_id:string;source_name:string;content:string;score:number}>=[];
if((guardrails.prohibitedTopics??[]).some(topic=>input.prompt.toLowerCase().includes(topic.toLowerCase()))){outcome="blocked";handoffReason="prohibited_topic"}else if(guardrails.handoffOnSensitiveIntent!==false&&sensitive.test(input.prompt)){outcome="handoff";handoffReason="sensitive_or_human_request"}else{const{data,error}=await client.rpc("search_agent_knowledge",{p_agent_id:agentId,p_query:input.prompt,p_limit:5});if(error)throw error;citations=(data??[]) as typeof citations;if(citations[0]){score=confidence(input.prompt,citations[0].content);if(score>=Number(agent.confidence_threshold)){response=citations[0].content.slice(0,1200)}else{outcome="handoff";handoffReason="confidence_below_threshold"}}else{outcome="handoff";handoffReason="missing_source"}}
const{data:evaluation,error}=await client.from("agent_evaluations").insert({tenant_id:input.tenantId,agent_id:agentId,prompt:input.prompt,response,confidence:score,citation_ids:citations.map(item=>item.chunk_id),outcome,handoff_reason:handoffReason,created_by:user.id}).select("id,created_at").single();if(error)throw error;return ok({evaluationId:evaluation.id,outcome,response,confidence:score,citations:citations.map(item=>({sourceId:item.source_id,sourceName:item.source_name,excerpt:item.content.slice(0,240)})),handoffReason},id)}catch(error){return failure(error,id)}}
